services:
  - type: web
    name: waste-to-feast
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_GEMINI_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    env: node
    nodeVersion: 18 